# Generated by Django 5.0.2 on 2026-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["display_order", "-id"],
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="author",
            name="focus_areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="author",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="author",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="author",
            name="telegram",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="author",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(default="Backend", max_length=50),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="work",
            name="features",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="work",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="work",
            name="results",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="work",
            name="summary",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, upload_to="author"),
        ),
        migrations.AlterField(
            model_name="author",
            name="lastname",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="work",
            name="image",
            field=models.ImageField(blank=True, upload_to="works"),
        ),
        migrations.AlterField(
            model_name="work",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
