# Generated by Django 5.0.2 on 2026-03-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_alter_work_options_author_email_author_focus_areas_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="architecture",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="work",
            name="github_url",
            field=models.URLField(blank=True),
        ),
    ]
