# Generated by Django 5.0.2 on 2026-03-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_work_architecture_work_github_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("problem", models.TextField()),
                ("solution", models.TextField()),
                ("stack", models.TextField()),
                ("metrics", models.TextField(blank=True)),
                ("architecture", models.TextField(blank=True)),
                ("github_link", models.URLField(blank=True)),
                ("demo_link", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_studies",
                        to="portfolio.work",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case study",
                "verbose_name_plural": "Case studies",
                "ordering": ["-featured", "-updated_at"],
            },
        ),
    ]
